name: LateX PR1, PR2 to PDF

# run on any push, any branch
on: [push]

# job to run, ref: https://github.com/thomas-chauvet/cv_latex/blob/main/.github/workflows/latex2pdf.yml
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX PR1
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main-pr1.tex
          latexmk_use_lualatex: true
      - name: Compile LaTeX PR2
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main-pr2.tex
          latexmk_use_lualatex: true
      - name: Arrange output
        run: |
          mkdir -p output
          mv main-pr1.pdf output/main-pr1.pdf
          mv main-pr2.pdf output/main-pr2.pdf
      - name: Upload PR1,2 in PDF to the workflow tab
        id: upload-workflow-tab-1
        uses: actions/upload-artifact@v4
        with:
          name: project1-project2
          path: output/main-*.pdf
