name: LateX PR1, PR2 to PDF

# run on any push, any branch
on: [push]

# job to run, ref: https://github.com/thomas-chauvet/cv_latex/blob/main/.github/workflows/latex2pdf.yml
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX PR1
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: project1/
          root_file: main.tex
          latexmk_use_lualatex: true
      - name: Arrange output
        run: |
          mkdir -p project1/output
          mv project1/main.pdf project1/output/main.pdf
      - name: Upload PR1 in PDF to the workflow tab
        id: upload-workflow-tab-1
        uses: actions/upload-artifact@v4
        with:
          name: project1
          path: project1/output/main.pdf
      - name: Compile LaTeX PR2
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: project2/
          root_file: main.tex
          latexmk_use_lualatex: true
      - name: Arrange output
        run: |
          mkdir -p project2/output
          mv project2/main.pdf project2/output/main.pdf
      - name: Upload PR2 in PDF to the workflow tab
        id: upload-workflow-tab-2
        uses: actions/upload-artifact@v4
        with:
          name: project2
          path: project2/output/main.pdf
